import Head from 'next/head';
import { useEffect } from 'react';
import { useAppDispatch, useAppSelector } from '../store';
import { adminActions } from '../store/adminSlice';
import LoginScreen from 'modules/LoginScreen';

const Index = () => {
  const isLoggedIn = useAppSelector((state) => state.admin.isLoggedIn);
  const isFirstTime = useAppSelector((state) => state.admin.isFirstTime);
  const dispatch = useAppDispatch();

  useEffect(() => {
    if (isLoggedIn && isFirstTime) {
      dispatch(adminActions.firstLoginDone(false));
    }
  }, [dispatch, isFirstTime, isLoggedIn]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginScreen />
    </>
  );
};

export default Index;
