/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import type { Context } from './api/context';

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {}

export interface NexusGenEnums {
  AdminRole: 'ADMIN' | 'SUPER_ADMIN';
  OrderStatus: 'CANCELLED' | 'DELIVERED' | 'ORDERED';
}

export interface NexusGenScalars {
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  Date: any;
  DateTime: any;
}

export interface NexusGenObjects {
  Admin: {
    // root type
    email: string; // String!
    firstName: string; // String!
    id: string; // ID!
    lastName: string; // String!
    passwordHash: string; // String!
    refreshToken?: string | null; // String
    role: NexusGenEnums['AdminRole']; // AdminRole!
    username: string; // String!
  };
  Customer: {
    // root type
    age?: number | null; // Int
    email: string; // String!
    firstName: string; // String!
    id: string; // ID!
    lastName: string; // String!
    passwordHash: string; // String!
    username: string; // String!
  };
  Item: {
    // root type
    description: string; // String!
    id: string; // ID!
    name: string; // String!
    price: number; // Float!
  };
  ItemInOrder: {
    // root type
    id: string; // ID!
    quantity: number; // Int!
    total: number; // Float!
  };
  Mutation: {};
  Order: {
    // root type
    address: string; // String!
    id: string; // ID!
    orderDate: NexusGenScalars['DateTime']; // DateTime!
    referenceId: string; // String!
    status: NexusGenEnums['OrderStatus']; // OrderStatus!
    total: number; // Float!
  };
  Query: {};
}

export interface NexusGenInterfaces {}

export interface NexusGenUnions {}

export type NexusGenRootTypes = NexusGenObjects;

export type NexusGenAllTypes = NexusGenRootTypes &
  NexusGenScalars &
  NexusGenEnums;

export interface NexusGenFieldTypes {
  Admin: {
    // field return type
    email: string; // String!
    firstName: string; // String!
    id: string; // ID!
    lastName: string; // String!
    passwordHash: string; // String!
    refreshToken: string | null; // String
    role: NexusGenEnums['AdminRole']; // AdminRole!
    username: string; // String!
  };
  Customer: {
    // field return type
    age: number | null; // Int
    email: string; // String!
    firstName: string; // String!
    id: string; // ID!
    lastName: string; // String!
    orders: NexusGenRootTypes['Order'][]; // [Order!]!
    passwordHash: string; // String!
    username: string; // String!
  };
  Item: {
    // field return type
    description: string; // String!
    id: string; // ID!
    itemInOrders: NexusGenRootTypes['ItemInOrder'][]; // [ItemInOrder!]!
    name: string; // String!
    price: number; // Float!
  };
  ItemInOrder: {
    // field return type
    id: string; // ID!
    itemView: NexusGenRootTypes['Item']; // Item!
    order: NexusGenRootTypes['Order'] | null; // Order
    quantity: number; // Int!
    total: number; // Float!
  };
  Mutation: {
    // field return type
    adminLogin: string | null; // String
    adminLogout: string | null; // String
    customerCreateOne: NexusGenRootTypes['Customer'] | null; // Customer
  };
  Order: {
    // field return type
    address: string; // String!
    customer: NexusGenRootTypes['Customer']; // Customer!
    id: string; // ID!
    itemsInOrder: NexusGenRootTypes['ItemInOrder'][]; // [ItemInOrder!]!
    orderDate: NexusGenScalars['DateTime']; // DateTime!
    referenceId: string; // String!
    status: NexusGenEnums['OrderStatus']; // OrderStatus!
    total: number; // Float!
  };
  Query: {
    // field return type
    adminGet: NexusGenRootTypes['Admin'] | null; // Admin
    adminGetMany: Array<NexusGenRootTypes['Admin'] | null> | null; // [Admin]
    customerGetMany: Array<NexusGenRootTypes['Customer'] | null> | null; // [Customer]
    customerGetOne: NexusGenRootTypes['Customer'] | null; // Customer
    getNewAccessToken: string | null; // String
    helloWorld: string | null; // String
  };
}

export interface NexusGenFieldTypeNames {
  Admin: {
    // field return type name
    email: 'String';
    firstName: 'String';
    id: 'ID';
    lastName: 'String';
    passwordHash: 'String';
    refreshToken: 'String';
    role: 'AdminRole';
    username: 'String';
  };
  Customer: {
    // field return type name
    age: 'Int';
    email: 'String';
    firstName: 'String';
    id: 'ID';
    lastName: 'String';
    orders: 'Order';
    passwordHash: 'String';
    username: 'String';
  };
  Item: {
    // field return type name
    description: 'String';
    id: 'ID';
    itemInOrders: 'ItemInOrder';
    name: 'String';
    price: 'Float';
  };
  ItemInOrder: {
    // field return type name
    id: 'ID';
    itemView: 'Item';
    order: 'Order';
    quantity: 'Int';
    total: 'Float';
  };
  Mutation: {
    // field return type name
    adminLogin: 'String';
    adminLogout: 'String';
    customerCreateOne: 'Customer';
  };
  Order: {
    // field return type name
    address: 'String';
    customer: 'Customer';
    id: 'ID';
    itemsInOrder: 'ItemInOrder';
    orderDate: 'DateTime';
    referenceId: 'String';
    status: 'OrderStatus';
    total: 'Float';
  };
  Query: {
    // field return type name
    adminGet: 'Admin';
    adminGetMany: 'Admin';
    customerGetMany: 'Customer';
    customerGetOne: 'Customer';
    getNewAccessToken: 'String';
    helloWorld: 'String';
  };
}

export interface NexusGenArgTypes {
  Mutation: {
    adminLogin: {
      // args
      password: string; // String!
      username: string; // String!
    };
    customerCreateOne: {
      // args
      age?: number | null; // Int
      email: string; // String!
      firstName: string; // String!
      lastName: string; // String!
      password: string; // String!
      username: string; // String!
    };
  };
  Query: {
    customerGetMany: {
      // args
      filter?: string | null; // ID
    };
    customerGetOne: {
      // args
      id: string; // ID!
    };
  };
}

export interface NexusGenAbstractTypeMembers {}

export interface NexusGenTypeInterfaces {}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false;
    resolveType: true;
    __typename: false;
  };
};

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames'];
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames'];
  allNamedTypes:
    | NexusGenTypes['allInputTypes']
    | NexusGenTypes['allOutputTypes'];
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginInputFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginSchemaConfig {}
  interface NexusGenPluginArgConfig {}
}
